### ISSUE TITLE
No modules_2_0

### ISSUE THREAD

**Issue by mvadari** [ismailof/mopidy-json-client#21]
I'm trying to run this code on a Mopidy server I'm involved in maintaining and I'm having a ModuleNotFound error that I can't seem to resolve: 

```
Traceback (most recent call last):
  File "cleartracks.py", line 4, in <module>
    mopidy = MopidyClient(ws_url="URL_OF_THE_SERVER")
  File "C:\Users\mvada\Documents\Anaconda\lib\site-packages\mopidy_json_client\client.py", line 244, in __init__
    MopidyAPI.set_version(version)
  File "C:\Users\mvada\Documents\Anaconda\lib\site-packages\mopidy_json_client\mopidy_api.py", line 21, in set_version
    import methods_2_0 as methods
ModuleNotFoundError: No module named 'methods_2_0'
```

How do I resolve this issue?

**Comment by AsbjornOlling** [comment]
This can be fixed by changing line 21 in mopidy_json_client/mopidy_api.py 

from

`import methods_2_0 as methods`

to

`from . import methods_2_0 as methods`

I'm in the middle of trying to use this (very nice) library for a mopidy client I'm writing. I might submit a pull request with my changes when I'm done.

**Comment by AsbjornOlling** [comment]
Actually now that I'm looking at the forks of this repo, I see that there are several forks that fix this (and more) python 2 / 3 issues. Just apparently nobody issued a pull request. hm.. 

Time to kick some life back into this project?

**Comment by AsbjornOlling** [comment]
Okay I ended up just writing my own library instead, which is both pip-installable and supports modern python.

https://github.com/AsbjornOlling/mopidyapi
