### ISSUE TITLE
No 'now playing' event on Pi Musicbox

### ISSUE THREAD

**Issue by eoware** [ismailof/mopidy-json-client#23]
Installed and ran the now_playing example script on a Pi MusicBox. The log indicates it connects fine:
[CONNECTION] Connecting to Mopidy Server at ws://localhost:6680/mopidy/ws
[CONNECTION] Mopidy Server is connected at ws://localhost:6680/mopidy/ws

When I start playing via Spotify Connect or Airplay, no event is generated.

**Comment by eoware** [comment]
Never mind, this looks to be due to Pi MusicBox not actually using Mopidy for some of the play-to options. I build a quick and dirty C# app and don't get the events with it either.

**Comment by ismailof** [comment]
I'll close it then, thanks!
